const data = [
    {
        "name": "National Means Cum-Merit Scholarship Scheme 2025",
        "provider": "Government of India",
        "application_deadline": "2025-02-20T00:00:00Z",
        "gender_applicable": ["male", "female", "transgender"],
        "caste_eligibility": ["SC/ST"],
        "studies_field_eligibility": ["below 10th"],
        "total_award_amount": 12000,
        "time_of_disburse": 1,
        "amount_per_disburse": 12000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://www.xyzinstitute.com/scholarships/engineering-bc"
    },
    {
        "name": "L’Oreal India For Young Women In Science Scholarship 2024-2025",
        "provider": "L’Oreal India",
        "application_deadline": "2025-01-31T00:00:00Z",
        "gender_applicable": ["female"],
        "caste_eligibility": ["OC"],
        "studies_field_eligibility": ["B.Tech", "B.E"],
        "total_award_amount": 250000,
        "time_of_disburse": 1,
        "amount_per_disburse": 250000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://www.buddy4study.com/page/loreal-india-for-young-women-in-science-scholarships"
    },
    {
        "name": "Post Matric Scholarship for OBC Students, Tripura 2024/25",
        "provider": "Government of Tripura",
        "application_deadline": "2025-01-31T00:00:00Z",
        "gender_applicable": ["male", "female", "transgender"],
        "caste_eligibility": ["BC"],
        "studies_field_eligibility": ["B.Com", "B.E", "B.Tech"],
        "total_award_amount": 50000,
        "time_of_disburse": 1,
        "amount_per_disburse": 50000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://www.wemakescholars.com/scholarship/post-matric-scholarship-for-obc-students-tripura"
    },
    {
        "name": "Vyasakabi Fakirmohan Bhasabruti Scholarship 2025",
        "provider": "Government of Odisha",
        "application_deadline": "2025-01-22T00:00:00Z",
        "gender_applicable": ["male", "female", "transgender"],
        "caste_eligibility": ["OC"],
        "studies_field_eligibility": ["B.Com", "B.E", "B.Tech"],
        "total_award_amount": 20000,
        "time_of_disburse": 1,
        "amount_per_disburse": 20000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://scholarshiplearn.com/vyasakabi-fakir-mohan-bhasabruti/",
    },
    {
        "name": "AICTE YASHASVI Scholarship 2025",
        "provider": "All India Council for Technical Education",
        "application_deadline": "2025-02-15T00:00:00Z",
        "gender_applicable": ["male", "female", "transgender"],
        "caste_eligibility": ["BC", "MBC", "OC", "SC/ST"],
        "studies_field_eligibility": ["B.E", "B.Tech"],
        "total_award_amount": 50000,
        "time_of_disburse": 1,
        "amount_per_disburse": 50000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://yashasvi.aicte.gov.in/login.php?r=session_invalid"
    },
    {
        "name": "Aditya Birla Scholarship 2024/25",
        "provider": "Aditya Birla Group",
        "application_deadline": "2025-02-20T00:00:00Z",
        "gender_applicable": ["male", "female", "transgender"],
        "caste_eligibility": ["OC"],
        "studies_field_eligibility": ["B.E", "B.Tech", "B.Com"],
        "total_award_amount": 180000,
        "time_of_disburse": 1,
        "amount_per_disburse": 180000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://www.buddy4study.com/page/aditya-birla-capital-scholarship"
    },
    {
        "name": "Sanskriti - Geddes Scholarship 2025",
        "provider": "Sanskriti Foundation",
        "application_deadline": "2025-02-20T00:00:00Z",
        "gender_applicable": ["male", "female", "transgender"],
        "caste_eligibility": ["OC"],
        "studies_field_eligibility": ["B.E", "B.Tech"],
        "total_award_amount": 45000,
        "time_of_disburse": 1,
        "amount_per_disburse": 45000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "http://www.sanskritifoundation.org/Geddes-Fellowship.html"
    },
    {
        "name": "Study Abroad Excellence Award 2025",
        "provider": "WeMakeScholars",
        "application_deadline": "2025-02-20T00:00:00Z",
        "gender_applicable": ["male", "female", "transgender"],
        "caste_eligibility": ["OC"],
        "studies_field_eligibility": ["B.E", "B.Tech", "B.Com"],
        "total_award_amount": 100000,
        "time_of_disburse": 1,
        "amount_per_disburse": 100000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://www.thesaea.org/"
    },
    {
        "name": "Nehru Study Abroad Scholarship 2025",
        "provider": "WeMakeScholars",
        "application_deadline": "2025-02-20T00:00:00Z",
        "gender_applicable": ["male", "female", "transgender"],
        "caste_eligibility": ["OC"],
        "studies_field_eligibility": ["B.E", "B.Tech", "B.Com"],
        "total_award_amount": 100000,
        "time_of_disburse": 1,
        "amount_per_disburse": 100000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://www.nehruscholarship.org/"
    },
    {
        "name": "Royal Society International Exchange Programme 2025",
        "provider": "Royal Society",
        "application_deadline": "2025-03-12T00:00:00Z",
        "gender_applicable": ["male", "female", "transgender"],
        "caste_eligibility": ["OC"],
        "studies_field_eligibility": ["B.E", "B.Tech", "B.Com"],
        "total_award_amount": 12000,
        "time_of_disburse": 1,
        "amount_per_disburse": 12000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://royalsociety.org/grants/international-exchanges/"
    },
    {
        "name": "NLB Scholarship 2025",
        "provider": "National Library Board, Singapore",
        "application_deadline": "2025-03-21T00:00:00Z",
        "gender_applicable": ["male", "female", "transgender"],
        "caste_eligibility": ["OC"],
        "studies_field_eligibility": ["B.E", "B.Tech", "B.Com"],
        "total_award_amount": 50000,
        "time_of_disburse": 1,
        "amount_per_disburse": 50000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://www.nlb.gov.sg/main/about-us/careers/scholarship"
    },
    {
        "name": "HDFC Educational Crisis Scholarship 2025",
        "provider": "HDFC Bank",
        "application_deadline": "2025-02-28T00:00:00Z",
        "gender_applicable": ["male", "female", "transgender"],
        "caste_eligibility": ["BC", "MBC", "SC/ST"],
        "studies_field_eligibility": ["B.E", "B.Tech", "M.E"],
        "total_award_amount": 75000,
        "time_of_disburse": 1,
        "amount_per_disburse": 75000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://www.buddy4study.com/page/hdfc-bank-parivartans-ecss-programme"
    },
    {
        "name": "Kotak Kanya Scholarship 2025",
        "provider": "Kotak Education Foundation",
        "application_deadline": "2025-03-15T00:00:00Z",
        "gender_applicable": ["female"],
        "caste_eligibility": ["BC", "MBC", "SC/ST"],
        "studies_field_eligibility": ["B.E", "B.Tech", "B.Com"],
        "total_award_amount": 100000,
        "time_of_disburse": 1,
        "amount_per_disburse": 100000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://www.buddy4study.com/page/kotak-kanya-scholarship"
    },
    {
        "name": "Tata Trusts Medical and Healthcare Scholarship 2025",
        "provider": "Tata Trusts",
        "application_deadline": "2025-03-10T00:00:00Z",
        "gender_applicable": ["male", "female", "transgender"],
        "caste_eligibility": ["OC"],
        "studies_field_eligibility": ["B.Tech", "M.E"],
        "total_award_amount": 200000,
        "time_of_disburse": 2,
        "amount_per_disburse": 100000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://scholarshiplearn.com/tata-trust-medical-and-healthcare-scholarship/"
    },
    {
        "name": "ONGC Scholarship for SC/ST Students 2025",
        "provider": "Oil and Natural Gas Corporation (ONGC)",
        "application_deadline": "2025-02-28T00:00:00Z",
        "gender_applicable": ["male", "female", "transgender"],
        "caste_eligibility": ["SC/ST"],
        "studies_field_eligibility": ["B.E", "B.Tech", "B.Com"],
        "total_award_amount": 48000,
        "time_of_disburse": 4,
        "amount_per_disburse": 12000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://www.buddy4study.com/article/ongc-scholarship"
    },
    {
        "name": "Dr. Abdul Kalam Scholarship for Academic Excellence 2025",
        "provider": "Dr. Abdul Kalam Foundation",
        "application_deadline": "2025-02-25T00:00:00Z",
        "gender_applicable": ["male", "female", "transgender"],
        "caste_eligibility": ["OC", "BC"],
        "studies_field_eligibility": ["B.E", "B.Tech", "M.E"],
        "total_award_amount": 100000,
        "time_of_disburse": 1,
        "amount_per_disburse": 100000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://scholarshiplearn.com/dr-apj-abdul-kalam-scholarship/"
    },
    {
        "name": "Fulbright-Nehru Master’s Fellowship 2025",
        "provider": "United States-India Educational Foundation (USIEF)",
        "application_deadline": "2025-05-15T00:00:00Z",
        "gender_applicable": ["male", "female", "transgender"],
        "caste_eligibility": ["OC"],
        "studies_field_eligibility": ["M.E"],
        "total_award_amount": 200000,
        "time_of_disburse": 1,
        "amount_per_disburse": 200000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://usief.org.in/Fulbright-Nehru-Fellowships.aspx"
    },
    {
        "name": "Erasmus Mundus Scholarship 2025",
        "provider": "European Commission",
        "application_deadline": "2025-03-30T00:00:00Z",
        "gender_applicable": ["male", "female", "transgender"],
        "caste_eligibility": ["OC"],
        "studies_field_eligibility": ["M.E"],
        "total_award_amount": 500000,
        "time_of_disburse": 2,
        "amount_per_disburse": 250000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://www.emhrpp.com/how-to-apply#application"
    },
    {
        "name": "National Overseas Scholarship for SC/ST Students 2025",
        "provider": "Government of India",
        "application_deadline": "2025-06-30T00:00:00Z",
        "gender_applicable": ["male", "female", "transgender"],
        "caste_eligibility": ["SC/ST"],
        "studies_field_eligibility": ["M.E"],
        "total_award_amount": 1000000,
        "time_of_disburse": 2,
        "amount_per_disburse": 500000,
        "scheme": "yearly",
        "applied_people": [],
        "application_link": "https://socialjustice.gov.in/schemes/28"
    }
]

module.exports = data;
